package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// Room is one interview. It is the durable record of a session; the live
// document lives in a hub goroutine and is not persisted here (yet).
type Room struct {
	ID        string
	OwnerID   int64
	Title     string
	Language  string
	// Prompt is the interview question. Only the owner may change it.
	Prompt    string
	CreatedAt time.Time
	// ClosedAt is nil while the room still accepts joins.
	ClosedAt *time.Time
}

// Open reports whether the room still accepts new participants.
func (r *Room) Open() bool { return r.ClosedAt == nil }

// CreateRoom inserts a room owned by ownerID.
//
// The ID is generated by the caller rather than the database: it has to be
// unguessable, and it has to satisfy the same pattern the WebSocket handler
// enforces. A CHECK constraint backs that up, so a bad ID fails here rather
// than at upgrade time.
func (s *Store) CreateRoom(ctx context.Context, id string, ownerID int64, title, language string, inviteTokenHash []byte) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		INSERT INTO rooms (id, owner_id, title, language, invite_token_hash)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, owner_id, title, language, prompt, created_at, closed_at
	`, id, ownerID, title, language, inviteTokenHash).
		Scan(&r.ID, &r.OwnerID, &r.Title, &r.Language, &r.Prompt, &r.CreatedAt, &r.ClosedAt)
	if err != nil {
		return nil, fmt.Errorf("store: create room: %w", err)
	}
	return &r, nil
}

// RoomByID fetches a room regardless of who owns it. Callers that act on
// behalf of an interviewer must still check OwnerID.
func (s *Store) RoomByID(ctx context.Context, id string) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		SELECT id, owner_id, title, language, prompt, created_at, closed_at
		FROM rooms
		WHERE id = $1
	`, id).Scan(&r.ID, &r.OwnerID, &r.Title, &r.Language, &r.Prompt, &r.CreatedAt, &r.ClosedAt)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: room by id: %w", err)
	}
	return &r, nil
}

// RoomByInvite resolves a candidate's link: the room ID from the path and the
// token from the query must both match, and the room must still be open.
//
// Both halves are checked in one query so a caller cannot accidentally
// validate the token against a different room than the one being joined.
func (s *Store) RoomByInvite(ctx context.Context, id string, inviteTokenHash []byte) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		SELECT id, owner_id, title, language, prompt, created_at, closed_at
		FROM rooms
		WHERE id = $1 AND invite_token_hash = $2 AND closed_at IS NULL
	`, id, inviteTokenHash).
		Scan(&r.ID, &r.OwnerID, &r.Title, &r.Language, &r.Prompt, &r.CreatedAt, &r.ClosedAt)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: room by invite: %w", err)
	}
	return &r, nil
}

// RoomsByOwner lists an interviewer's rooms, newest first.
func (s *Store) RoomsByOwner(ctx context.Context, ownerID int64, limit int) ([]Room, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, owner_id, title, language, prompt, created_at, closed_at
		FROM rooms
		WHERE owner_id = $1
		ORDER BY created_at DESC
		LIMIT $2
	`, ownerID, limit)
	if err != nil {
		return nil, fmt.Errorf("store: rooms by owner: %w", err)
	}
	defer rows.Close()

	// Non-nil so an interviewer with no rooms encodes as [] rather than null,
	// which the dashboard would have to special-case.
	out := []Room{}
	for rows.Next() {
		var r Room
		if err := rows.Scan(&r.ID, &r.OwnerID, &r.Title, &r.Language, &r.Prompt, &r.CreatedAt, &r.ClosedAt); err != nil {
			return nil, fmt.Errorf("store: scan room: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: rooms by owner: %w", err)
	}
	return out, nil
}

// CloseRoom marks a room finished. Scoped to ownerID so one interviewer
// cannot close another's room; a miss is ErrNotFound either way, which keeps
// "does not exist" and "not yours" indistinguishable to the caller.
func (s *Store) CloseRoom(ctx context.Context, id string, ownerID int64) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET closed_at = now()
		WHERE id = $1 AND owner_id = $2 AND closed_at IS NULL
	`, id, ownerID)
	if err != nil {
		return fmt.Errorf("store: close room: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdatePrompt changes the interview question.
//
// Scoped to ownerID: a candidate holding an invite must not be able to rewrite
// the question they are being asked. The WebSocket enforces the same rule for
// the live relay; this is the durable half.
func (s *Store) UpdatePrompt(ctx context.Context, id string, ownerID int64, prompt string) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET prompt = $3
		WHERE id = $1 AND owner_id = $2
	`, id, ownerID, prompt)
	if err != nil {
		return fmt.Errorf("store: update prompt: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// RotateInvite replaces a room's invite token, revoking any link already sent.
func (s *Store) RotateInvite(ctx context.Context, id string, ownerID int64, inviteTokenHash []byte) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET invite_token_hash = $3
		WHERE id = $1 AND owner_id = $2
	`, id, ownerID, inviteTokenHash)
	if err != nil {
		return fmt.Errorf("store: rotate invite: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}
