package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

// Room is one interview. It is the durable record of a session; the live
// document lives in a hub goroutine and is not persisted here (yet).
type Room struct {
	ID       string
	OwnerID  int64
	Title    string
	Language string
	// Prompt is the interview question. Only the owner may change it.
	Prompt string
	// ScheduledAt is when the interviewer means to hold it. Advisory — the
	// timer runs from StartedAt, not from this.
	ScheduledAt *time.Time
	// Duration is how long the interview may run once it starts.
	Duration time.Duration
	// StartedAt is set the first time anyone joins. Nil until then, which is
	// what distinguishes a booked room from a live one.
	StartedAt *time.Time
	// durationMinutes is the raw column, converted into Duration after each
	// scan. Unexported so callers cannot read the unit by accident.
	durationMinutes int
	CreatedAt       time.Time
	// ClosedAt is nil while the room still accepts joins.
	ClosedAt *time.Time
}

// Open reports whether the room still accepts new participants.
func (r *Room) Open() bool { return r.ClosedAt == nil }

// EndsAt is when the interview must stop, or the zero time if it has not
// started yet. The deadline runs from the first join rather than from the
// booking, so a room created on Monday and used on Friday still gets its full
// time.
func (r *Room) EndsAt() time.Time {
	if r.StartedAt == nil {
		return time.Time{}
	}
	return r.StartedAt.Add(r.Duration)
}

// Expired reports whether the interview has run out of time.
func (r *Room) Expired() bool {
	ends := r.EndsAt()
	return !ends.IsZero() && time.Now().After(ends)
}

// minutes is how duration_minutes is stored; the Go side works in Duration so
// nothing above here has to remember the unit.
func (r *Room) minutes() int { return int(r.Duration / time.Minute) }

// hydrate turns the raw columns into the shapes the rest of the code uses.
// Call it after every successful scan; scanRoom and this are a pair.
func (r *Room) hydrate() { r.Duration = time.Duration(r.durationMinutes) * time.Minute }

// scanRoom lists the destinations for a row, in the column order every query
// in this file uses. One place, so adding a column cannot half-land.
func scanRoom(r *Room) []any {
	return []any{
		&r.ID, &r.OwnerID, &r.Title, &r.Language, &r.Prompt,
		&r.ScheduledAt, &r.durationMinutes, &r.StartedAt, &r.CreatedAt, &r.ClosedAt,
	}
}

// CreateRoom inserts a room owned by ownerID.
//
// The ID is generated by the caller rather than the database: it has to be
// unguessable, and it has to satisfy the same pattern the WebSocket handler
// enforces. A CHECK constraint backs that up, so a bad ID fails here rather
// than at upgrade time.
// NewRoom is what CreateRoom needs. A struct rather than eight positional
// arguments, which is where a title and a language get silently swapped.
type NewRoom struct {
	ID              string
	OwnerID         int64
	Title           string
	Language        string
	Prompt          string
	ScheduledAt     *time.Time
	Duration        time.Duration
	InviteTokenHash []byte
}

func (s *Store) CreateRoom(ctx context.Context, in NewRoom) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		INSERT INTO rooms (id, owner_id, title, language, prompt, scheduled_at, duration_minutes, invite_token_hash)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
	`, in.ID, in.OwnerID, in.Title, in.Language, in.Prompt, in.ScheduledAt,
		int(in.Duration/time.Minute), in.InviteTokenHash).
		Scan(scanRoom(&r)...)
	if err != nil {
		return nil, fmt.Errorf("store: create room: %w", err)
	}
	r.hydrate()
	return &r, nil
}

// CreateRoomWithinPlan performs the quota check and insert in one transaction,
// serialised on the owner's row so concurrent requests cannot both pass the
// count-then-insert window.
func (s *Store) CreateRoomWithinPlan(ctx context.Context, in NewRoom, max int, lifetime bool) (*Room, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("store: begin room quota: %w", err)
	}
	defer tx.Rollback(ctx)
	var used int
	query := `SELECT count(*) FROM rooms WHERE owner_id = $1`
	if !lifetime {
		query += ` AND created_at >= date_trunc('month', now())`
	}
	if err := tx.QueryRow(ctx, `SELECT id FROM users WHERE id = $1 FOR UPDATE`, in.OwnerID).Scan(new(int64)); err != nil {
		return nil, fmt.Errorf("store: lock owner: %w", err)
	}
	if err := tx.QueryRow(ctx, query, in.OwnerID).Scan(&used); err != nil {
		return nil, fmt.Errorf("store: count rooms: %w", err)
	}
	if used >= max {
		return nil, ErrQuotaExceeded
	}
	var r Room
	if err := tx.QueryRow(ctx, `
		INSERT INTO rooms (id, owner_id, title, language, prompt, scheduled_at, duration_minutes, invite_token_hash)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
		RETURNING id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
	`, in.ID, in.OwnerID, in.Title, in.Language, in.Prompt, in.ScheduledAt, int(in.Duration/time.Minute), in.InviteTokenHash).Scan(scanRoom(&r)...); err != nil {
		return nil, fmt.Errorf("store: create room: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("store: commit room: %w", err)
	}
	r.hydrate()
	return &r, nil
}

// StartRoom stamps the moment the interview actually began, the first time
// anybody joins, and returns the room either way.
//
// COALESCE rather than a read-then-write: both people may arrive within the
// same millisecond, and doing it in one statement means the first write wins
// and the second is a no-op instead of moving the deadline.
func (s *Store) StartRoom(ctx context.Context, id string) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		UPDATE rooms
		SET started_at = COALESCE(started_at, now())
		WHERE id = $1
		RETURNING id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
	`, id).Scan(scanRoom(&r)...)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: start room: %w", err)
	}
	r.hydrate()
	return &r, nil
}

// CountRooms reports how many interviews an owner has created, either for all
// time or within the current calendar month.
//
// Counted from the rooms table rather than a separate usage counter: the rooms
// *are* the record, and a counter would be one more thing to keep in step with
// them.
func (s *Store) CountRooms(ctx context.Context, ownerID int64, lifetime bool) (int, error) {
	query := `SELECT count(*) FROM rooms WHERE owner_id = $1`
	if !lifetime {
		query += ` AND created_at >= date_trunc('month', now())`
	}

	var n int
	if err := s.pool.QueryRow(ctx, query, ownerID).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count rooms: %w", err)
	}
	return n, nil
}

// UsedDuration totals the time interviews actually ran, for the same window.
// Rooms that never started contribute nothing — a booking is not usage.
func (s *Store) UsedDuration(ctx context.Context, ownerID int64, lifetime bool) (time.Duration, error) {
	query := `
		SELECT COALESCE(SUM(EXTRACT(EPOCH FROM (COALESCE(closed_at, now()) - started_at))), 0)
		FROM rooms
		WHERE owner_id = $1 AND started_at IS NOT NULL`
	if !lifetime {
		query += ` AND created_at >= date_trunc('month', now())`
	}

	var seconds float64
	if err := s.pool.QueryRow(ctx, query, ownerID).Scan(&seconds); err != nil {
		return 0, fmt.Errorf("store: used duration: %w", err)
	}
	return time.Duration(seconds) * time.Second, nil
}

// RoomByID fetches a room regardless of who owns it. Callers that act on
// behalf of an interviewer must still check OwnerID.
func (s *Store) RoomByID(ctx context.Context, id string) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		SELECT id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
		FROM rooms
		WHERE id = $1
	`, id).Scan(scanRoom(&r)...)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: room by id: %w", err)
	}
	r.hydrate()
	return &r, nil
}

// RoomByInvite resolves a candidate's link: the room ID from the path and the
// token from the query must both match, and the room must still be open.
//
// Both halves are checked in one query so a caller cannot accidentally
// validate the token against a different room than the one being joined.
func (s *Store) RoomByInvite(ctx context.Context, id string, inviteTokenHash []byte) (*Room, error) {
	var r Room
	err := s.pool.QueryRow(ctx, `
		SELECT id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
		FROM rooms
		WHERE id = $1 AND invite_token_hash = $2 AND closed_at IS NULL
		  AND (started_at IS NULL OR started_at + (duration_minutes * interval '1 minute') > now())
	`, id, inviteTokenHash).
		Scan(scanRoom(&r)...)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: room by invite: %w", err)
	}
	r.hydrate()
	return &r, nil
}

// RoomsByOwner lists an interviewer's rooms, newest first.
func (s *Store) RoomsByOwner(ctx context.Context, ownerID int64, limit int) ([]Room, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, owner_id, title, language, prompt, scheduled_at, duration_minutes, started_at, created_at, closed_at
		FROM rooms
		WHERE owner_id = $1
		ORDER BY created_at DESC
		LIMIT $2
	`, ownerID, limit)
	if err != nil {
		return nil, fmt.Errorf("store: rooms by owner: %w", err)
	}
	defer rows.Close()

	// Non-nil so an interviewer with no rooms encodes as [] rather than null,
	// which the dashboard would have to special-case.
	out := []Room{}
	for rows.Next() {
		var r Room
		if err := rows.Scan(scanRoom(&r)...); err != nil {
			return nil, fmt.Errorf("store: scan room: %w", err)
		}
		r.hydrate()
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: rooms by owner: %w", err)
	}
	return out, nil
}

// CloseRoom marks a room finished. Scoped to ownerID so one interviewer
// cannot close another's room; a miss is ErrNotFound either way, which keeps
// "does not exist" and "not yours" indistinguishable to the caller.
func (s *Store) CloseRoom(ctx context.Context, id string, ownerID int64) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET closed_at = now()
		WHERE id = $1 AND owner_id = $2 AND closed_at IS NULL
	`, id, ownerID)
	if err != nil {
		return fmt.Errorf("store: close room: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdatePrompt changes the interview question.
//
// Scoped to ownerID: a candidate holding an invite must not be able to rewrite
// the question they are being asked. The WebSocket enforces the same rule for
// the live relay; this is the durable half.
func (s *Store) UpdatePrompt(ctx context.Context, id string, ownerID int64, prompt string) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET prompt = $3
		WHERE id = $1 AND owner_id = $2
	`, id, ownerID, prompt)
	if err != nil {
		return fmt.Errorf("store: update prompt: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// RotateInvite replaces a room's invite token, revoking any link already sent.
func (s *Store) RotateInvite(ctx context.Context, id string, ownerID int64, inviteTokenHash []byte) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE rooms SET invite_token_hash = $3
		WHERE id = $1 AND owner_id = $2
	`, id, ownerID, inviteTokenHash)
	if err != nil {
		return fmt.Errorf("store: rotate invite: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// CloseExpiredRoom records that an interview ran out of time.
//
// Not scoped to an owner: this is the server closing a room on the clock, not
// a person acting on one. Already-closed rooms are left alone, so an
// interviewer who ended it early keeps their timestamp rather than having it
// overwritten by the deadline passing a moment later.
func (s *Store) CloseExpiredRoom(ctx context.Context, id string) error {
	if _, err := s.pool.Exec(ctx, `
		UPDATE rooms SET closed_at = now()
		WHERE id = $1 AND closed_at IS NULL
	`, id); err != nil {
		return fmt.Errorf("store: close expired room: %w", err)
	}
	return nil
}
